### ISSUE TITLE
并发时会有问题

### ISSUE THREAD

**Issue by mydatebin** [tangaiyun/RedisRateLimiter#1]
并发时，get和限流操作并不是一个原子操作，lua执行把get和限流都放到一个lua执行，这是一个原子操作
   private static final String LuaSecondsScript = " local key = KEYS[1]; "
            + " local limit = tonumber(ARGV[2]);"
            + " local current = tonumber(redis.call('get', key) or 0);"
            + " if current + 1 > limit then  return 0; "
            + " else  redis.call('incr',KEYS[1]);  redis.call('expire',KEYS[1],ARGV[1]); return 1;"
            + " end ";

**Comment by tangaiyun** [comment]
并发问题已解决，欢迎使用和提出修改意见
